title: Project Page

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          text:
            label: Project description
            type: textarea
            inline: true

  sidebar:
    width: 1/3
    sections:
      images:
        type: files
        layout: list
        image:
          back: black
