name: 'Deploy on push'

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

jobs:
  ploi-deploy:
    name: 'Ploi Deploy'
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@v3
      
    - name: Setup PHP with composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: gd ctype curl mbstring
        tools: composer

    - name: Deploy
      uses: Glennmen/ploi-deploy-action@v1.2.0
      with:
        webhook_url: ${{ secrets.WEBHOOK_URL }}
